server:
  port: 8080

spring:
  application:
    name: movies-api
  datasource:
    driver-class-name: org.h2.Driver
    initialization-mode: never
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    